version: '3.8'

services:
  frontend:
    build:
      context: ./vuejs-ezops-test
      dockerfile: Dockerfile
    image: felipe0599/teste-ezops-cloud-frontend:latest
    ports:
      - "8080:8080"   # Expose frontend port 8080
    volumes:
      - ./vuejs-ezops-test:/app
    networks:
      - app_network

  backend:
    build:
      context: ./rest-api-ezops-test
      dockerfile: Dockerfile
    image: felipe0599/teste-ezops-cloud-backend:latest
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=mydatabase
    ports:
      - "3000:3000"   # Expose RestAPI port 3000
    volumes:
      - ./rest-api-ezops-test:/app
    networks:
      - app_network
    depends_on:
      - postgres

  postgres:
    image: postgres:11
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
      POSTGRES_PORT: 5432 
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
